In [1]:
from google.colab import files
uploaded = files.upload()

Saving synthetic_online_retail_data.csv to synthetic_online_retail_data.csv

In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('synthetic_online_retail_data.csv')

df.head()

,customer_id,order_date,product_id,category_id,category_name,product_name,quantity,price,payment_method,city,review_score,gender,age
0,13542,2024-12-17,784,10,Electronics,Smartphone,2,373.36,Credit Card,New Oliviaberg,1.0,F,56
1,23188,2024-06-01,682,50,Sports & Outdoors,Soccer Ball,5,299.34,Credit Card,Port Matthew,NaN,M,59
2,55098,2025-02-04,684,50,Sports & Outdoors,Tent,5,23.00,Credit Card,West Sarah,5.0,F,64
3,65208,2024-10-28,204,40,Books & Stationery,Story Book,2,230.11,Bank Transfer,Hernandezburgh,5.0,M,34
4,63872,2024-05-10,202,20,Fashion,Skirt,4,176.72,Credit Card,Jenkinshaven,1.0,F,33

In [4]:
print(df.shape)

df.info()

df.isnull().sum()

(1000, 13)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   customer_id     1000 non-null   int64
 1   order_date      1000 non-null   object
 2   product_id      1000 non-null   int64
 3   category_id     1000 non-null   int64
 4   category_name   1000 non-null   object
 5   product_name    1000 non-null   object
 6   quantity        1000 non-null   int64
 7   price           1000 non-null   float64
 8   payment_method  1000 non-null   object
 9   city            1000 non-null   object
 10  review_score    799 non-null    float64
 11  gender          897 non-null    object
 12  age             1000 non-null   int64
dtypes: float64(2), int64(5), object(6)
memory usage: 101.7+ KB

customer_id         0
order_date          0
product_id          0
category_id         0
category_name       0
product_name        0
quantity            0
price               0
payment_method      0
city                0
review_score      201
gender            103
age                 0
dtype: int64

In [5]:
df['review_score'].fillna(df['review_score'].median(), inplace=True)

/tmp/ipykernel_335/3948919218.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['review_score'].fillna(df['review_score'].median(), inplace=True)

In [6]:
df['gender'].fillna(df['gender'].mode()[0], inplace=True)

/tmp/ipykernel_335/1062339567.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['gender'].fillna(df['gender'].mode()[0], inplace=True)

In [7]:
df.isnull().sum()

customer_id       0
order_date        0
product_id        0
category_id       0
category_name     0
product_name      0
quantity          0
price             0
payment_method    0
city              0
review_score      0
gender            0
age               0
dtype: int64

In [8]:
df.drop_duplicates(inplace=True)

print("Duplicates Removed")

Duplicates Removed

In [9]:
df['order_date'] = pd.to_datetime(df['order_date'])

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   customer_id     1000 non-null   int64
 1   order_date      1000 non-null   datetime64[ns]
 2   product_id      1000 non-null   int64
 3   category_id     1000 non-null   int64
 4   category_name   1000 non-null   object
 5   product_name    1000 non-null   object
 6   quantity        1000 non-null   int64
 7   price           1000 non-null   float64
 8   payment_method  1000 non-null   object
 9   city            1000 non-null   object
 10  review_score    1000 non-null   float64
 11  gender          1000 non-null   object
 12  age             1000 non-null   int64
dtypes: datetime64[ns](1), float64(2), int64(5), object(5)
memory usage: 101.7+ KB

In [10]:
df.to_csv('cleaned_online_retail_data.csv', index=False)

print("Data Cleaning Completed")

Data Cleaning Completed

In [11]:
from google.colab import files

files.download('cleaned_online_retail_data.csv')